### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by Mathopenevse** [yp87/leaf2mqtt#76]
**Describe the bug**
hi, since few days i receive no data from server and after restart, logs show this message : "WARNING: 2024-05-17 11:48:58.277755: main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.
WARNING: 2024-05-17 11:48:58.277829: main: Could not execute request."

i have check on my phone and all it's correct, it's possible that the bug come from nissan... 

maybe someone have the same problem to confirm ?

**LEAF_TYPE**
newerThanMay2019

**Expected behavior**

**Comment by juhjar** [comment]
Same here..

**Comment by Jopand** [comment]
I'm having the same issue with an "olderEurope" leaf:

WARNING: 2024-05-18 07:21:31.682400: main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.
FINE: 2024-05-18 07:21:31.682439: main: FormatException: Unexpected character (at character 1)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

Logging in from the app still works

**Comment by Derich367** [comment]
It seems, that Nissan changed the login Client-secret.
This should fix it: 
https://gitlab.com/tobiaswkjeldsen/dartnissanconnect/-/commit/e0301993e872a63c059c3afaa258b413d435fe0e

**Comment by Mathopenevse** [comment]
Thanks for your answer! the leaf2mqtt project import the dartnissanconnect library so i try to delete my container and build it again to import the corrected library but it doesn't fix the problem...

**Comment by Happyboy0980** [comment]
Did you import all the new files or only the connect one ?

**Comment by Derich367** [comment]
This repo is currently using the dartnissanconnect fork from sensor-freak (https://gitlab.com/sensor-freak/dartnissanconnect).
This doesn't have my mentioned fix yet. We cannot use tobias original repository, cause of additional features added by sensor-freak.
I forked the repository and merged the changes from tobias and built the container again.
Now it's working for me again.

You could use my repository, to build the leaf2mqtt container againg, until sensor-freak merged the changes: https://github.com/Derich367/dartnissanconnect

**Comment by ItorJames** [comment]
> It seems, that Nissan changed the login Client-secret. This should fix it: https://gitlab.com/tobiaswkjeldsen/dartnissanconnect/-/commit/e0301993e872a63c059c3afaa258b413d435fe0e

How can this be implemented? Do we need to wait for a new version or is this something the average user can do? I note the path doesn’t even exist in my HA file explorer so I have no idea how to make the change.

**Comment by Happyboy0980** [comment]
For my 2018 40kwh Leaf I first use the HA own module again with this update : 

https://github.com/filcole/pycarwings2/issues/46

I forked this repro, and updated all to the same as the "MyLeaf" app. 
But some how it still seems to use the old ones.

**Comment by Derich367** [comment]
> > It seems, that Nissan changed the login Client-secret. This should fix it: https://gitlab.com/tobiaswkjeldsen/dartnissanconnect/-/commit/e0301993e872a63c059c3afaa258b413d435fe0e
> 
> How can this be implemented? Do we need to wait for a new version or is this something the average user can do? I note the path doesn’t even exist in my HA file explorer so I have no idea how to make the change.

As a fast solution you can switch to my fork: https://github.com/Derich367/leaf2mqtt.
I don't want to create a pull-request here, cause the fix is just changing the dependency to another fork.
The real fix would be, that the dependency includes the fix.

As yp87 mentioned in the readme, the more active fork is: https://github.com/kamikac/leaf2mqtt
He is also maintaining a own nissanconnet fork, where i created a pull request with the fix from tobias: https://github.com/kamiKAC/dartnissanconnect/issues/1

**Comment by Mathopenevse** [comment]
> This repo is currently using the dartnissanconnect fork from sensor-freak (https://gitlab.com/sensor-freak/dartnissanconnect). This doesn't have my mentioned fix yet. We cannot use tobias original repository, cause of additional features added by sensor-freak. I forked the repository and merged the changes from tobias and built the container again. Now it's working for me again.
> 
> You could use my repository, to build the leaf2mqtt container againg, until sensor-freak merged the changes: https://github.com/Derich367/dartnissanconnect

thanks for your fork! it work for me now!

**Comment by ItorJames** [comment]
> > > It seems, that Nissan changed the login Client-secret. This should fix it: https://gitlab.com/tobiaswkjeldsen/dartnissanconnect/-/commit/e0301993e872a63c059c3afaa258b413d435fe0e
> > 
> > 
> > How can this be implemented? Do we need to wait for a new version or is this something the average user can do? I note the path doesn’t even exist in my HA file explorer so I have no idea how to make the change.
> 
> As a fast solution you can switch to my fork: https://github.com/Derich367/leaf2mqtt. I don't want to create a pull-request here, cause the fix is just changing the dependency to another fork. The real fix would be, that the dependency includes the fix.
> 
> As yp87 mentioned in the readme, the more active fork is: https://github.com/kamikac/leaf2mqtt He is also maintaining a own nissanconnet fork, where i created a pull request with the fix from tobias: [kamiKAC/dartnissanconnect#1](https://github.com/kamiKAC/dartnissanconnect/issues/1)

Thanks. I’ve no idea how to switch to a new fork though.

**Comment by Derich367** [comment]
> Thanks. I’ve no idea how to switch to a new fork though.

You can uninstall the ha addon and install it than again via the button on the repo [page] (https://github.com/Derich367/leaf2mqtt). 
Note: that you have to configure the again after you installed it.

**Comment by MerthurX** [comment]
> > Thanks. I’ve no idea how to switch to a new fork though.
> 
> You can uninstall the ha addon and install it than again via the button on the repo [page] (https://github.com/Derich367/leaf2mqtt). Note: that you have to configure the again after you installed it.

I have removed yp87/leaf2mqtt and added yours derich367/leaf2mqtt image to my docker, but when I try to run docker container from CMD with following command:

docker run --restart always -e LEAF_USERNAME=myusername -e LEAF_PASSWORD=mypassword -e LEAF_TYPE=olderEurope -e MQTT_HOST=192.168.0.100 -e UPDATE_INTERVAL_MINUTES=1440 -e COMMAND_ATTEMPTS=5 --name leaf2mqtt derich367/leaf2mqtt:latest

I still get the same login error:

WARNING: 2024-05-19 19:06:52.722528: main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.

Any idea what am I doing wrong?

**Comment by Mathopenevse** [comment]
> > > Thanks. I’ve no idea how to switch to a new fork though.
> > 
> > 
> > You can uninstall the ha addon and install it than again via the button on the repo [page] (https://github.com/Derich367/leaf2mqtt). Note: that you have to configure the again after you installed it.
> 
> I have removed yp87/leaf2mqtt and added yours derich367/leaf2mqtt image to my docker, but when I try to run docker container from CMD with following command:
> 
> docker run --restart always -e LEAF_USERNAME=myusername -e LEAF_PASSWORD=mypassword -e LEAF_TYPE=olderEurope -e MQTT_HOST=192.168.0.100 -e UPDATE_INTERVAL_MINUTES=1440 -e COMMAND_ATTEMPTS=5 --name leaf2mqtt derich367/leaf2mqtt:latest
> 
> I still get the same login error:
> 
> WARNING: 2024-05-19 19:06:52.722528: main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.
> 
> Any idea what am I doing wrong?

are you sure you are in the good case to run the command?

**Comment by Derich367** [comment]
> > > Thanks. I’ve no idea how to switch to a new fork though.
> > 
> > 
> > You can uninstall the ha addon and install it than again via the button on the repo [page] (https://github.com/Derich367/leaf2mqtt). Note: that you have to configure the again after you installed it.
> 
> I have removed yp87/leaf2mqtt and added yours derich367/leaf2mqtt image to my docker, but when I try to run docker container from CMD with following command:
> 
> docker run --restart always -e LEAF_USERNAME=myusername -e LEAF_PASSWORD=mypassword -e LEAF_TYPE=olderEurope -e MQTT_HOST=192.168.0.100 -e UPDATE_INTERVAL_MINUTES=1440 -e COMMAND_ATTEMPTS=5 --name leaf2mqtt derich367/leaf2mqtt:latest
> 
> I still get the same login error:
> 
> WARNING: 2024-05-19 19:06:52.722528: main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.
> 
> Any idea what am I doing wrong?

You are using the olderEurope type. The mentioned fixed just belongs to nissanConnect api (newerThan2019).
It seems that nissan has changed the api for old type too.
I updated the related library with the new url and created a new leaf2mqtt version.
Feel free to test, if it is now working, cause i can only verify the newerThan2019 type.

**Comment by MerthurX** [comment]
> > > > Thanks. I’ve no idea how to switch to a new fork though.
> > > 
> > > 
> > > You can uninstall the ha addon and install it than again via the button on the repo [page] (https://github.com/Derich367/leaf2mqtt). Note: that you have to configure the again after you installed it.
> > 
> > 
> > I have removed yp87/leaf2mqtt and added yours derich367/leaf2mqtt image to my docker, but when I try to run docker container from CMD with following command:
> > docker run --restart always -e LEAF_USERNAME=myusername -e LEAF_PASSWORD=mypassword -e LEAF_TYPE=olderEurope -e MQTT_HOST=192.168.0.100 -e UPDATE_INTERVAL_MINUTES=1440 -e COMMAND_ATTEMPTS=5 --name leaf2mqtt derich367/leaf2mqtt:latest
> > I still get the same login error:
> > WARNING: 2024-05-19 19:06:52.722528: main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.
> > Any idea what am I doing wrong?
> 
> You are using the olderEurope type. The mentioned fixed just belongs to nissanConnect api (newerThan2019). It seems that nissan has changed the api for old type too. I updated the related library with the new url and created a new leaf2mqtt version. Feel free to test, if it is now working, cause i can only verify the newerThan2019 type.

yes I have 2nd GEN LEAF from 2018, I was using command mentioned in my previous post with yp87/leaf2mqtt version and everything was working fine until few days ago (btw I can login to My Leaf app without problems)

I have tried with your updated image right now but I am still getting the same error massage.

**Comment by rogeralexanderdean** [comment]
2nd gen LEAF 2018 working this morning as OlderEurope on https://github.com/Derich367/leaf2mqtt v6. Previously I had the same error as MerthurX above. Thanks very much!

**Comment by MerthurX** [comment]
V6 now works for me also. Thank you very much Derich367!

**Comment by Mathopenevse** [comment]
there is new update from nissan connect today and the problem is come back...

**Comment by Derich367** [comment]
> there is new update from nissan connect today and the problem is come back...

I'm using the newerThanMay2019 type like you, and i have no issues so far.
Is it the same error log like before? Is the Nissan Connect app working for you?

**Comment by Mathopenevse** [comment]
> > there is new update from nissan connect today and the problem is come back...
> 
> I'm using the newerThanMay2019 type like you, and i have no issues so far. Is it the same error log like before? Is the Nissan Connect app working for you?

i fix the problem after deleted and reinstalled the container, i have this log in the terminal : 

![Capture d’écran 2024-05-25 à 10 04 50](https://github.com/yp87/leaf2mqtt/assets/130982702/edfffc93-68e5-4bd2-94e6-cf77659a1905)


nissan connect working well but i have to update the app twice in 2 days

**Comment by MerthurX** [comment]
V6 is still working for me without any issues.

**Comment by Mathopenevse** [comment]
it's not my case : i have to remove and restart container every day coz it's freezing and i have the same warning log when i restart...

**Comment by ItorJames** [comment]
> > Thanks. I’ve no idea how to switch to a new fork though.
> 
> You can uninstall the ha addon and install it than again via the button on the repo [page] (https://github.com/Derich367/leaf2mqtt). Note: that you have to configure the again after you installed it.



> > Thanks. I’ve no idea how to switch to a new fork though.
> 
> You can uninstall the ha addon and install it than again via the button on the repo [page] (https://github.com/Derich367/leaf2mqtt). Note: that you have to configure the again after you installed it.

Thanks. Finally got round to doing this and it worked instantly. Great stuff.

**Comment by zipperten** [comment]
Hi i My leaf2mqtt plugin stoped 16May 2024, 
With the android app "My Leaf" it do not work with Europe as region but with World as region it do work. "is World the same as newerThanMAy2019 in Leef2MQTT?"

When i installed [](https://github.com/Derich367/leaf2mqtt) it worked!

**Comment by reidmswartz** [comment]
I just tried installing Derich's V6 fresh in HA and am getting the same login error. Newer than 2019 Leaf in US. Anyone else getting the error still?
```
WARNING: main: An error occured while logging in. Please make sure you have selected the right LEAF_TYPE, LEAF_USERNAME and LEAF_PASSWORD. Retrying in 5 seconds.
WARNING: main: Could not execute request.
```

**Comment by MerthurX** [comment]
Nissan did some API changes again and leaf2mqtt stopped working, can this be fixed/updated? thanks!
